# Generated by Django 6.0.6 on 2026-07-27 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        choices=[("buy", "Buy"), ("rent", "Rent")],
                        default="buy",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("live", "Live"),
                            ("sold", "Sold"),
                            ("rented", "Rented"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_duplicate_flagged", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="listings.listing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "city",
                    models.CharField(
                        db_index=True, default="Ahmedabad", max_length=100
                    ),
                ),
                (
                    "sub_market",
                    models.CharField(
                        blank=True,
                        help_text="Sub-market or cluster area",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("locality", models.CharField(db_index=True, max_length=150)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("Apartment", "Apartment"),
                            ("Independent House", "Independent House"),
                            ("Villa", "Villa"),
                            ("Plot", "Plot"),
                            ("Commercial", "Commercial"),
                        ],
                        db_index=True,
                        default="Apartment",
                        max_length=50,
                    ),
                ),
                ("bhk", models.IntegerField(default=2)),
                ("area_sqft", models.FloatField(help_text="Total area in square feet")),
                ("floor", models.IntegerField(default=0)),
                ("total_floors", models.IntegerField(default=1)),
                ("age_years", models.IntegerField(default=0)),
                (
                    "furnishing",
                    models.CharField(
                        choices=[
                            ("Unfurnished", "Unfurnished"),
                            ("Semi-Furnished", "Semi-Furnished"),
                            ("Fully Furnished", "Fully Furnished"),
                        ],
                        default="Unfurnished",
                        max_length=30,
                    ),
                ),
                (
                    "facing",
                    models.CharField(
                        choices=[
                            ("East", "East"),
                            ("West", "West"),
                            ("North", "North"),
                            ("South", "South"),
                            ("North-East", "North-East"),
                            ("South-East", "South-East"),
                            ("North-West", "North-West"),
                            ("South-West", "South-West"),
                        ],
                        default="East",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(db_index=True, decimal_places=2, max_digits=12),
                ),
                (
                    "rera_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("dist_metro_km", models.FloatField(blank=True, null=True)),
                ("dist_school_km", models.FloatField(blank=True, null=True)),
                ("dist_hospital_km", models.FloatField(blank=True, null=True)),
                ("dist_it_hub_km", models.FloatField(blank=True, null=True)),
                ("has_gym", models.BooleanField(default=False)),
                ("has_pool", models.BooleanField(default=False)),
                ("has_clubhouse", models.BooleanField(default=False)),
                ("has_security", models.BooleanField(default=False)),
                ("has_power_backup", models.BooleanField(default=False)),
                ("has_parking", models.BooleanField(default=False)),
                ("has_lift", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Properties",
                "indexes": [
                    models.Index(
                        fields=["city", "property_type", "price"],
                        name="listings_pr_city_7e0daa_idx",
                    ),
                    models.Index(
                        fields=["locality", "bhk"],
                        name="listings_pr_localit_b99fd7_idx",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="listings.property",
            ),
        ),
        migrations.CreateModel(
            name="InvestmentListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expected_roi_percentage",
                    models.FloatField(help_text="Expected Annual ROI %"),
                ),
                (
                    "projected_rental_yield",
                    models.FloatField(help_text="Projected Rental Yield %"),
                ),
                (
                    "min_investment_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("lock_in_period_months", models.IntegerField(default=12)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investment_details",
                        to="listings.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="property_images/"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="External URL or S3 URL", null=True
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="listings.property",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-is_primary"],
            },
        ),
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("query_params", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiteVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preferred_date", models.DateField()),
                ("preferred_time", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_visits",
                        to="listings.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="listings.property",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "property")},
            },
        ),
    ]
