# Generated by Django 6.0.6 on 2026-07-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_investmentlisting_early_access_ends_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RERAProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rera_number",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "state_authority",
                    models.CharField(default="Gujarat RERA (GujRERA)", max_length=100),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("promoter_name", models.CharField(max_length=255)),
                (
                    "registration_status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved & Valid"),
                            ("delayed", "Timeline Delayed"),
                            ("under_review", "Under Renewal / Review"),
                            ("revoked", "Revoked / Blacklisted"),
                        ],
                        default="approved",
                        max_length=30,
                    ),
                ),
                (
                    "compliance_score",
                    models.IntegerField(
                        default=95, help_text="RERA Trust Index Score 0-100"
                    ),
                ),
                ("promised_completion_date", models.DateField(blank=True, null=True)),
                ("revised_completion_date", models.DateField(blank=True, null=True)),
                (
                    "escrow_verified",
                    models.BooleanField(
                        default=True, help_text="70% Buyer Fund Escrow Account Verified"
                    ),
                ),
                (
                    "escrow_bank_name",
                    models.CharField(
                        default="HDFC Bank Ltd (Escrow Branch)", max_length=150
                    ),
                ),
                (
                    "litigation_count",
                    models.IntegerField(
                        default=0, help_text="Active legal complaints count"
                    ),
                ),
                ("approved_floors", models.IntegerField(default=15)),
                ("total_units", models.IntegerField(default=120)),
                (
                    "official_portal_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "document_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
