# Generated by Django 6.0.6 on 2026-08-01 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_reraproject"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RERAProject",
        ),
    ]
