# Generated by Django 6.0.6 on 2026-08-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_password_reset_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_role_verified",
            field=models.BooleanField(
                default=False,
                help_text="Admin verified standing for Builder/Agent professional roles",
            ),
        ),
    ]
